// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInParams) Reset()         { *m = SignInParams{} }
func (m *SignInParams) String() string { return proto.CompactTextString(m) }
func (*SignInParams) ProtoMessage()    {}
func (*SignInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

func (m *SignInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInParams.Unmarshal(m, b)
}
func (m *SignInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInParams.Marshal(b, m, deterministic)
}
func (m *SignInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInParams.Merge(m, src)
}
func (m *SignInParams) XXX_Size() int {
	return xxx_messageInfo_SignInParams.Size(m)
}
func (m *SignInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInParams.DiscardUnknown(m)
}

var xxx_messageInfo_SignInParams proto.InternalMessageInfo

func (m *SignInParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SignInResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshAccessTokenParams struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenParams) Reset()         { *m = RefreshAccessTokenParams{} }
func (m *RefreshAccessTokenParams) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenParams) ProtoMessage()    {}
func (*RefreshAccessTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{2}
}

func (m *RefreshAccessTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenParams.Unmarshal(m, b)
}
func (m *RefreshAccessTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenParams.Marshal(b, m, deterministic)
}
func (m *RefreshAccessTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenParams.Merge(m, src)
}
func (m *RefreshAccessTokenParams) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenParams.Size(m)
}
func (m *RefreshAccessTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenParams proto.InternalMessageInfo

func (m *RefreshAccessTokenParams) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshAccessTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenResponse) Reset()         { *m = RefreshAccessTokenResponse{} }
func (m *RefreshAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenResponse) ProtoMessage()    {}
func (*RefreshAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{3}
}

func (m *RefreshAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenResponse.Unmarshal(m, b)
}
func (m *RefreshAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenResponse.Merge(m, src)
}
func (m *RefreshAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenResponse.Size(m)
}
func (m *RefreshAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenResponse proto.InternalMessageInfo

func (m *RefreshAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshAccessTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type VerifyAccessTokenParams struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAccessTokenParams) Reset()         { *m = VerifyAccessTokenParams{} }
func (m *VerifyAccessTokenParams) String() string { return proto.CompactTextString(m) }
func (*VerifyAccessTokenParams) ProtoMessage()    {}
func (*VerifyAccessTokenParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{4}
}

func (m *VerifyAccessTokenParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAccessTokenParams.Unmarshal(m, b)
}
func (m *VerifyAccessTokenParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAccessTokenParams.Marshal(b, m, deterministic)
}
func (m *VerifyAccessTokenParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAccessTokenParams.Merge(m, src)
}
func (m *VerifyAccessTokenParams) XXX_Size() int {
	return xxx_messageInfo_VerifyAccessTokenParams.Size(m)
}
func (m *VerifyAccessTokenParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAccessTokenParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAccessTokenParams proto.InternalMessageInfo

func (m *VerifyAccessTokenParams) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type VerifyAccessTokenResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAccessTokenResponse) Reset()         { *m = VerifyAccessTokenResponse{} }
func (m *VerifyAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyAccessTokenResponse) ProtoMessage()    {}
func (*VerifyAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{5}
}

func (m *VerifyAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAccessTokenResponse.Unmarshal(m, b)
}
func (m *VerifyAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAccessTokenResponse.Merge(m, src)
}
func (m *VerifyAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyAccessTokenResponse.Size(m)
}
func (m *VerifyAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAccessTokenResponse proto.InternalMessageInfo

func (m *VerifyAccessTokenResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyAccessTokenResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyAccessTokenResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VerifyAccessTokenResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*SignInParams)(nil), "pepeunlimited.authentication.SignInParams")
	proto.RegisterType((*SignInResponse)(nil), "pepeunlimited.authentication.SignInResponse")
	proto.RegisterType((*RefreshAccessTokenParams)(nil), "pepeunlimited.authentication.RefreshAccessTokenParams")
	proto.RegisterType((*RefreshAccessTokenResponse)(nil), "pepeunlimited.authentication.RefreshAccessTokenResponse")
	proto.RegisterType((*VerifyAccessTokenParams)(nil), "pepeunlimited.authentication.VerifyAccessTokenParams")
	proto.RegisterType((*VerifyAccessTokenResponse)(nil), "pepeunlimited.authentication.VerifyAccessTokenResponse")
}

func init() { proto.RegisterFile("authentication.proto", fileDescriptor_d0dbc99083440df2) }

var fileDescriptor_d0dbc99083440df2 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcf, 0x8b, 0xd3, 0x40,
	0x18, 0x25, 0x46, 0x5b, 0xfb, 0x59, 0x05, 0x87, 0x4a, 0x63, 0x14, 0xa9, 0xf1, 0x52, 0x44, 0x52,
	0x50, 0xfc, 0x71, 0x10, 0xa4, 0x1e, 0x84, 0xde, 0x24, 0x15, 0x11, 0x2f, 0x65, 0x9a, 0x7c, 0x6d,
	0x87, 0x4d, 0x66, 0x86, 0x99, 0x64, 0x4b, 0x61, 0x6f, 0x0b, 0x7b, 0xd8, 0xbf, 0x7a, 0x49, 0x26,
	0xcd, 0x6e, 0x37, 0xdb, 0xec, 0x16, 0xf6, 0xf8, 0xbe, 0xef, 0xbd, 0x97, 0x17, 0xde, 0x37, 0xd0,
	0xa3, 0x59, 0xba, 0x42, 0x9e, 0xb2, 0x90, 0xa6, 0x4c, 0x70, 0x5f, 0x2a, 0x91, 0x0a, 0xf2, 0x5a,
	0xa2, 0xc4, 0x8c, 0xc7, 0x2c, 0x61, 0x29, 0x46, 0xfe, 0x2e, 0xc7, 0x7d, 0xb5, 0x14, 0x62, 0x19,
	0xe3, 0xa8, 0xe0, 0xce, 0xb3, 0xc5, 0x08, 0x13, 0x99, 0x6e, 0x8c, 0xd4, 0x7d, 0x73, 0x7d, 0xb9,
	0x56, 0x54, 0x4a, 0x54, 0xda, 0xec, 0xbd, 0x5f, 0xd0, 0x9d, 0xb2, 0x25, 0x9f, 0xf0, 0xdf, 0x54,
	0xd1, 0x44, 0x13, 0x17, 0x1e, 0x67, 0x1a, 0x15, 0xa7, 0x09, 0x3a, 0xd6, 0xc0, 0x1a, 0x76, 0x82,
	0x0a, 0xe7, 0x3b, 0x49, 0xb5, 0x5e, 0x0b, 0x15, 0x39, 0x0f, 0xcc, 0x6e, 0x8b, 0xbd, 0x7f, 0xf0,
	0xcc, 0xf8, 0x04, 0xa8, 0xa5, 0xe0, 0x1a, 0xc9, 0x5b, 0xe8, 0xd2, 0x30, 0x44, 0xad, 0x67, 0xa9,
	0x38, 0x42, 0x5e, 0xba, 0x3d, 0x31, 0xb3, 0x3f, 0xf9, 0x88, 0xbc, 0x83, 0xa7, 0x0a, 0x17, 0x0a,
	0xf5, 0xaa, 0xe4, 0x18, 0xd7, 0x6e, 0x39, 0x2c, 0x48, 0xde, 0x0f, 0x70, 0x02, 0x83, 0xc7, 0x97,
	0xd2, 0x32, 0x6d, 0xcd, 0xc0, 0xba, 0xc1, 0x20, 0x02, 0xb7, 0x6e, 0x70, 0xef, 0x31, 0xbf, 0x43,
	0xff, 0x2f, 0x2a, 0xb6, 0xd8, 0xd4, 0x53, 0xde, 0xfe, 0x09, 0xef, 0x04, 0x5e, 0xd6, 0xd4, 0x55,
	0xc4, 0xa6, 0x4e, 0x7a, 0xf0, 0x08, 0x13, 0xca, 0xe2, 0x32, 0x93, 0x01, 0xa4, 0x0f, 0xed, 0x9c,
	0x31, 0x63, 0x91, 0x63, 0x0f, 0xac, 0xa1, 0x1d, 0xb4, 0x72, 0x38, 0x89, 0x72, 0xba, 0x12, 0x31,
	0x6a, 0xe7, 0xe1, 0xc0, 0xce, 0xe9, 0x05, 0xf8, 0x78, 0x6e, 0xc3, 0x8b, 0xf1, 0xce, 0x51, 0x4d,
	0x51, 0x1d, 0xb3, 0x10, 0xc9, 0x1c, 0x5a, 0xa6, 0x56, 0xf2, 0xde, 0x6f, 0x3a, 0x42, 0xff, 0xea,
	0x11, 0xb9, 0x1f, 0xee, 0xc2, 0xad, 0x7e, 0xef, 0xcc, 0x02, 0x52, 0x2f, 0x88, 0x7c, 0x69, 0x36,
	0xd9, 0x77, 0x13, 0xee, 0xb7, 0x43, 0x75, 0x55, 0x90, 0x53, 0x0b, 0x9e, 0xd7, 0x5a, 0x20, 0x9f,
	0x9b, 0xfd, 0xf6, 0x94, 0xee, 0x7e, 0x3d, 0x50, 0xb6, 0x4d, 0xf1, 0xb3, 0xf3, 0xbf, 0xad, 0x64,
	0x98, 0xd3, 0xe7, 0xad, 0xe2, 0x8d, 0x7e, 0xba, 0x08, 0x00, 0x00, 0xff, 0xff, 0x31, 0xb9, 0x27,
	0x0d, 0x16, 0x04, 0x00, 0x00,
}
